# Generated by Django 3.0.2 on 2020-01-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('set_date', models.DateTimeField()),
                ('target_date', models.DateTimeField()),
                ('finished_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='goals/')),
                ('body', models.TextField()),
                ('set_back', models.TextField()),
                ('Jan', models.TextField()),
                ('Feb', models.TextField()),
            ],
        ),
    ]
