# Generated by Django 3.0.2 on 2020-01-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='Feb',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='goal',
            name='Jan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='goal',
            name='finished_date',
            field=models.DateField(blank=True, default='2020-12-31', null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='set_back',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='goal',
            name='set_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
